#%RAML 0.8
title: test-api
version: test-version
/root:
  get:
    displayName: getString
    responses:
      200:
        description: root get description
        body:
          application/json:
