#%RAML 0.8
title: test-api
version: v1
/root:
  displayName: root resource
  description: root resource description
  get:
    displayName: getString
    description: |
      root get description
      with multiple lines
    responses:
      200:
        body:
          application/json:
  put:
    displayName: putString
    responses:
      200:
        body:
          application/json:
