#%RAML 0.8
title: test-api
version: v1
/root:
  displayName: root resource
  description: root resource description
  get:
    displayName: getString
    description: |
      root get description
      with multiple lines
    responses:
      200:
        body:
          application/json:
  put:
    displayName: putString
    responses:
      200:
        body:
          application/json:
  /sub:
    get:
      displayName: sub get
    /sub:
      get:
        displayName: sub sub get
      /sub:
        get:
          displayName: sub sub sub get
  /othersub:
    get:
  /{path-param}:
    uriParameters:
      path-param:
        type: string
        displayName: pathParam
    get:
      displayName: getWithPathParam
