#%RAML 0.8
title: test-title
version: test-version
/p: 
    displayName: p-resource
    description: p-resource. something about the p.
    /{path-param}: 
        uriParameters: 
            path-param: 
                displayName: p
                description: p. p-param-descr
                type: integer
                required: true
                repeat: false
        get: 
            description: get action. method-doGet
            displayName: get-op
            headers: 
                header-param: 
                    displayName: h
                    description: h. h-param-descr
                    type: string
                    required: false
                    repeat: false
            queryParameters: 
                query-param: 
                    displayName: q
                    description: q. q-param-descr
                    type: string
                    required: false
                    repeat: false
                    enum: [A, B]
            body: 
                application/json: 
                    schema: |
                        {
                            "$schema":"http://json-schema.org/schema#",
                            "type":"object",
                            "id":"urn:jsonschema:com:github:t1:ramlap:test:Pojo",
                            "properties":{
                                "foo":{
                                    "type":"string"
                                },
                                "bar":{
                                    "type":"integer"
                                }
                            }
                        }
            responses: 
                "200": 
                    description: everything's fine
                    body: 
                        application/json: 
                            schema: |
                                {
                                    "$schema":"http://json-schema.org/schema#",
                                    "type":"array",
                                    "items":{
                                        "type":"object",
                                        "id":"urn:jsonschema:com:github:t1:ramlap:test:Pojo",
                                        "properties":{
                                            "foo":{
                                                "type":"string"
                                            },
                                            "bar":{
                                                "type":"integer"
                                            }
                                        }
                                    }
                                }
                "404": 
                    description: nothing there
                    body: 
                        application/json: 
                            schema: |
                                {
                                    "$schema":"http://json-schema.org/schema#",
                                    "type":"array",
                                    "items":{
                                        "type":"object",
                                        "id":"urn:jsonschema:com:github:t1:ramlap:test:Pojo",
                                        "properties":{
                                            "foo":{
                                                "type":"string"
                                            },
                                            "bar":{
                                                "type":"integer"
                                            }
                                        }
                                    }
                                }
                "400": 
                    description: your data is no good
                    body: 
                        application/problem+json: 
                            schema: |
                                {
                                    "$schema":"http://json-schema.org/schema#",
                                    "type":"object",
                                    "id":"urn:jsonschema:com:github:t1:ramlap:ProblemDetail:ValidationFailed",
                                    "properties":{
                                        "type":{
                                            "type":"string",
                                            "id":"urn:jsonschema:java:net:URI",
                                            "description":"A URI reference [RFC3986] that identifies the problem type. When dereferenced, it is encouraged to provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html401-19991224]). When this member is not present, its value is assumed to be \"about:blank\". <p> Defaults to the {@link #URN_PROBLEM_PREFIX} + \"java:\" + fully qualified class name."
                                        },
                                        "title":{
                                            "type":"string",
                                            "description":"A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization."
                                        },
                                        "status":{
                                            "type":"object",
                                            "id":"urn:jsonschema:javax:ws:rs:core:Response:StatusType",
                                            "properties":{
                                            },
                                            "description":"The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem."
                                        },
                                        "detail":{
                                            "type":"string",
                                            "description":"The full, human-readable explanation specific to this occurrence of the problem. It MAY change from occurrence to occurrence of the problem."
                                        },
                                        "instance":{
                                            "type":"string",
                                            "id":"urn:jsonschema:java:net:URI",
                                            "description":"A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced."
                                        }
                                    }
                                }
