#%RAML 0.8
title: test-title
version: test-version
/p: 
    displayName: p-resource
    description: p-resource. something about the p. 
    /{path-param}: 
        uriParameters: 
            path-param: 
                displayName: p
                description: p-param-descr
                type: integer
                required: true
                repeat: false
        get: 
            description: get action 
            displayName: get-op
            headers: 
                header-param: 
                    displayName: h
                    description: h-param-descr
                    type: string
                    required: false
                    repeat: false
            queryParameters: 
                query-param: 
                    displayName: q
                    description: q-param-descr
                    type: string
                    required: false
                    repeat: false
                    enum: [A, B]
            body: 
                application/json: 
                    schema: |
                        {
                            "type":"object",
                            "id":"urn:jsonschema:com:github:t1:ramlap:test:Pojo",
                            "properties":{
                                "foo":{
                                    "type":"string"
                                },
                                "bar":{
                                    "type":"string"
                                }
                            }
                        }
            responses: 
                "200": 
                    description: Success
                    body: 
                        application/json: 
                            schema: |
                                {
                                    "type":"string",
                                    "enum":[
                                        "A",
                                        "B"
                                    ]
                                }
